# Generated by Django 3.1.5 on 2021-01-15 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
