# Generated by Django 3.1.5 on 2021-01-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='nums_vacancies',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='nums_vacancies',
            field=models.IntegerField(null=True),
        ),
    ]
